import Nav from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeContext from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      {/*   Warning : Prop `className` did not match. Server: "__className_20951f dark" Client: "__className_20951f"  방지*/}
      <body className="h-full text-black transition-all duration-200 bg-white dark:bg-gray-900 dark:selection::bg-gray-900 dark:text-white selection:bg-gray-50">
        <ThemeContext>
          <Nav />
          <main className="max-w-3xl px-4 mx-auto sm:px-6 lg:px-8">
            {children}
          </main>
        </ThemeContext>
      </body>
    </html>
  );
}
