import Nav from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="h-full text-black bg-white dark:bg-gray-900 dark:selection::bg-gray-900 dark:text-white selection:bg-gray-50">
        <Nav />
        <main className="max-w-3xl px-4 max-auto sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
